### ISSUE TITLE
CRASH when app go in background

### ISSUE THREAD

**Issue by codingjeremy** [android/security-samples#21]
<a href="https://github.com/doffi88"><img src="https://avatars2.githubusercontent.com/u/23333375?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [doffi88](https://github.com/doffi88)**
_Tuesday Nov 08, 2016 at 09:38 GMT_
_Originally opened as https://github.com/googlesamples/android-FingerprintDialog/issues/42_

----

hy  guys, sorry for my english , I have this problem when I close authentication dialog and app go in background

D/AbstractTracker: Event success
E/System: Uncaught exception thrown by finalizer
E/System: java.lang.IllegalStateException: Binder has been finalized!
              at android.os.BinderProxy.transactNative(Native Method)
              at android.os.BinderProxy.transact(Binder.java:536)
              at android.security.IKeystoreService$Stub$Proxy.abort(IKeystoreService.java:1302)
              at android.security.KeyStore.abort(KeyStore.java:496)
              at android.security.keystore.AndroidKeyStoreCipherSpiBase.finalize(AndroidKeyStoreCipherSpiBase.java:680)
              at android.security.keystore.AndroidKeyStoreUnauthenticatedAESCipherSpi$CBC$PKCS7Padding.finalize(AndroidKeyStoreUnauthenticatedAESCipherSpi.java:73)
              at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:219)
              at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:197)
              at java.lang.Thread.run(Thread.java:818)

how can I resolve this issue?

thanks in advance

**Comment by codingjeremy** [comment]
<a href="https://github.com/IgorGanapolsky"><img src="https://avatars0.githubusercontent.com/u/201209?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [IgorGanapolsky](https://github.com/IgorGanapolsky)**
_Friday May 25, 2018 at 19:21 GMT_

----

I am getting the same error.  Is there a solution for this?

**Comment by nic0lette** [comment]
The sample was ported to use BiometricPrompt and so I'm hopeful that this issue would be resolved. If it's still occurring, please open another issue.
