### ISSUE TITLE
Physical Devices - At least one fingerprint must be enrolled to create keys requiring user authentication for every use.

### ISSUE THREAD

**Issue by codingjeremy** [android/security-samples#26]
<a href="https://github.com/zolbayars"><img src="https://avatars2.githubusercontent.com/u/3589907?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zolbayars](https://github.com/zolbayars)**
_Friday Jun 09, 2017 at 08:37 GMT_
_Originally opened as https://github.com/googlesamples/android-FingerprintDialog/issues/47_

----

The app is throwing an IllegalStateException on following physical devices with registered fingerprints: 

- Samsung S5 - SM-G800H (Android 6.0.1 API 23)
- Samsung Note 4 - SM-N9105S (Android 6.0.1 API 23)
- Samsung S6 Edge - SM-G925F (Android 6.0.1 API 23)

I tried these without success:
- Deleted all fingerprints and re-registered them again. (And setting screen lock with fingerprint)
- Updated Android SDK Build-Tools to the latest. 
- Restarted the devices

What should I do? 

Stacktrace:
```
06-09 16:24:59.682 6873-6873/com.example.android.fingerprintdialog E/AndroidRuntime: FATAL EXCEPTION: main
 Process: com.example.android.fingerprintdialog, PID: 6873
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android.fingerprintdialog/com.example.android.fingerprintdialog.MainActivity}: java.lang.RuntimeException: java.security.InvalidAlgorithmParameterException: java.lang.IllegalStateException: At least one fingerprint must be enrolled to create keys requiring user authentication for every use
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3319)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
 at android.app.ActivityThread.access$1100(ActivityThread.java:229)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:148)
 at android.app.ActivityThread.main(ActivityThread.java:7331)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
 Caused by: java.lang.RuntimeException: java.security.InvalidAlgorithmParameterException: java.lang.IllegalStateException: At least one fingerprint must be enrolled to create keys requiring user authentication for every use
 at com.example.android.fingerprintdialog.MainActivity.createKey(MainActivity.java:269)
 at com.example.android.fingerprintdialog.MainActivity.onCreate(MainActivity.java:152)
 at android.app.Activity.performCreate(Activity.java:6904)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415) 
 at android.app.ActivityThread.access$1100(ActivityThread.java:229) 
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
 at android.os.Handler.dispatchMessage(Handler.java:102) 
 at android.os.Looper.loop(Looper.java:148) 
 at android.app.ActivityThread.main(ActivityThread.java:7331) 
 at java.lang.reflect.Method.invoke(Native Method) 
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
 Caused by: java.security.InvalidAlgorithmParameterException: java.lang.IllegalStateException: At least one fingerprint must be enrolled to create keys requiring user authentication for every use
 at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineInit(AndroidKeyStoreKeyGeneratorSpi.java:238)
 at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi$AES.engineInit(AndroidKeyStoreKeyGeneratorSpi.java:53)
 at javax.crypto.KeyGenerator.init(KeyGenerator.java:189)
 at com.example.android.fingerprintdialog.MainActivity.createKey(MainActivity.java:265)
 at com.example.android.fingerprintdialog.MainActivity.onCreate(MainActivity.java:152) 
 at android.app.Activity.performCreate(Activity.java:6904) 
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136) 
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266) 
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415) 
 at android.app.ActivityThread.access$1100(ActivityThread.java:229) 
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
 at android.os.Handler.dispatchMessage(Handler.java:102) 
 at android.os.Looper.loop(Looper.java:148) 
 at android.app.ActivityThread.main(ActivityThread.java:7331) 
 at java.lang.reflect.Method.invoke(Native Method) 
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
 Caused by: java.lang.IllegalStateException: At least one fingerprint must be enrolled to create keys requiring user authentication for every use
 at android.security.keystore.KeymasterUtils.addUserAuthArgs(KeymasterUtils.java:115)
 at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineInit(AndroidKeyStoreKeyGeneratorSpi.java:234)
 at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi$AES.engineInit(AndroidKeyStoreKeyGeneratorSpi.java:53) 
 at javax.crypto.KeyGenerator.init(KeyGenerator.java:189) 
 at com.example.android.fingerprintdialog.MainActivity.createKey(MainActivity.java:265) 
 at com.example.android.fingerprintdialog.MainActivity.onCreate(MainActivity.java:152) 
 at android.app.Activity.performCreate(Activity.java:6904) 
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136) 
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266) 
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415) 
 at android.app.ActivityThread.access$1100(ActivityThread.java:229) 
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
 at android.os.Handler.dispatchMessage(Handler.java:102) 
 at android.os.Looper.loop(Looper.java:148) 
 at android.app.ActivityThread.main(ActivityThread.java:7331) 
 at java.lang.reflect.Method.invoke(Native Method) 
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 

```

**Comment by codingjeremy** [comment]
<a href="https://github.com/farhancroem"><img src="https://avatars2.githubusercontent.com/u/17467244?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [farhancroem](https://github.com/farhancroem)**
_Tuesday Jun 13, 2017 at 07:05 GMT_

----

It looks like android default API is not able to handle some Samsung devices.

**Comment by codingjeremy** [comment]
<a href="https://github.com/Tharkius"><img src="https://avatars2.githubusercontent.com/u/15523706?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tharkius](https://github.com/Tharkius)**
_Thursday May 23, 2019 at 11:39 GMT_

----

Two years later and the problem persists. Crashlytics lists me some occurrences for a Sony Xperia X device. Any suggestions?

**Comment by codingjeremy** [comment]
<a href="https://github.com/zolbayars"><img src="https://avatars2.githubusercontent.com/u/3589907?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zolbayars](https://github.com/zolbayars)**
_Friday May 24, 2019 at 04:18 GMT_

----

@Tharkius 
The workaround was using the Samsung Pass SDK if the device is Samsung's. Not really sure about Xperia.

**Comment by codingjeremy** [comment]
<a href="https://github.com/usantos"><img src="https://avatars0.githubusercontent.com/u/124369?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [usantos](https://github.com/usantos)**
_Thursday Jul 04, 2019 at 21:35 GMT_

----

Is not it because you're not trying to create the key when the fingerprint is not available?

**Comment by isaidamier** [comment]
Hi, we are reserving this site for questions about the sample apps specifically. For more general questions about Biometrics on Android, please use [StackOverflow with tag android-biometric](https://stackoverflow.com/questions/tagged/android-biometric).

Also this sample is being deprecated in favor of [BiometricLoginKotlin](https://github.com/android/security-samples/tree/biometriclogin)

**Comment by willlockwood** [comment]
> Also this sample is being deprecated in favor of [BiometricLoginKotlin](https://github.com/android/security-samples/tree/biometriclogin)

Heads up: this link has changed. You can now find the example at [BiometricLoginKotlin](https://github.com/android/security-samples/tree/main/BiometricLoginKotlin)

**Comment by charlesganza** [comment]
To anyone facing this issue, you have to wrap any logic that needs to create/access the keystore on whether or not biometrics authentication is possible on the device.
Example:
```val hasBiometricsCapability = biometricManager.canAuthenticate(BiometricManager.Authenticators.BIOMETRIC_STRONG) == BiometricManager.BIOMETRIC_SUCCESS

if(hasBiometricsCapability){
    //generate key or access key
}
```
