### ISSUE TITLE
Exception thrown after fingerprint app is closed ,as mentioned below

### ISSUE THREAD

**Issue by codingjeremy** [android/security-samples#29]
<a href="https://github.com/sairajkishore"><img src="https://avatars2.githubusercontent.com/u/29804566?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sairajkishore](https://github.com/sairajkishore)**
_Monday Aug 07, 2017 at 21:53 GMT_
_Originally opened as https://github.com/googlesamples/android-FingerprintDialog/issues/50_

----

java.lang.IllegalStateException: Binder has been finalized!
                                                                                   at android.os.BinderProxy.transactNative(Native Method)
                                                                                   at android.os.BinderProxy.transact(Binder.java:628)
                                                                                   at android.security.IKeystoreService$Stub$Proxy.abort(IKeystoreService.java:1387)
                                                                                   at android.security.KeyStore.abort(KeyStore.java:879)
                                                                                   at android.security.keystore.AndroidKeyStoreCipherSpiBase.finalize(AndroidKeyStoreCipherSpiBase.java:744)
                                                                                   at android.security.keystore.AndroidKeyStoreUnauthenticatedAESCipherSpi$CBC$PKCS7Padding.finalize(AndroidKeyStoreUnauthenticatedAESCipherSpi.java)
                                                                                   at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:222)
                                                                                   at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:209)
                                                                                   at java.lang.Thread.run(Thread.java:762)

**Comment by codingjeremy** [comment]
<a href="https://github.com/KalpeshJadvani"><img src="https://avatars3.githubusercontent.com/u/28008106?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [KalpeshJadvani](https://github.com/KalpeshJadvani)**
_Friday Sep 22, 2017 at 04:40 GMT_

----

also i got this error but i can't find 

why this happened

**Comment by codingjeremy** [comment]
<a href="https://github.com/srikanthnama"><img src="https://avatars0.githubusercontent.com/u/2804520?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [srikanthnama](https://github.com/srikanthnama)**
_Thursday Jun 21, 2018 at 11:21 GMT_

----

I also got the same issue

**Comment by codingjeremy** [comment]
<a href="https://github.com/hirenshah"><img src="https://avatars2.githubusercontent.com/u/418112?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hirenshah](https://github.com/hirenshah)**
_Wednesday Jan 02, 2019 at 18:05 GMT_

----

Anyone?

**Comment by codingjeremy** [comment]
<a href="https://github.com/jimmysuncpt"><img src="https://avatars1.githubusercontent.com/u/20553676?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jimmysuncpt](https://github.com/jimmysuncpt)**
_Thursday Jan 03, 2019 at 07:17 GMT_

----

me too

**Comment by nic0lette** [comment]
Dup of #21
