### ISSUE TITLE
Meizu crashed when using AndroidKeyStore

### ISSUE THREAD

**Issue by codingjeremy** [android/security-samples#33]
<a href="https://github.com/jimmysuncpt"><img src="https://avatars1.githubusercontent.com/u/20553676?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jimmysuncpt](https://github.com/jimmysuncpt)**
_Thursday Jan 03, 2019 at 07:30 GMT_
_Originally opened as https://github.com/googlesamples/android-FingerprintDialog/issues/54_

----

There are crashes in some Meizu phones, such as M5 note, PRO 7 Plus and so on. The system version is Android 7.0. The log is:
```
java.util.concurrent.TimeoutException: android.security.keystore.AndroidKeyStoreUnauthenticatedAESCipherSpi$CBC$PKCS7Padding.finalize(AndroidKeyStoreUnauthenticatedAESCipherSpi.java) timed out after 20 seconds
	at android.os.BinderProxy.transactNative(BinderProxy.java)
	at android.os.BinderProxy.transact(BinderProxy.java:626)
	at android.security.IKeystoreService$Stub$Proxy.abort(IKeystoreService.java:1341)
	at android.security.KeyStore.abort(KeyStore.java:538)
	at android.security.keystore.AndroidKeyStoreCipherSpiBase.finalize(AndroidKeyStoreCipherSpiBase.java:744)
	at android.security.keystore.AndroidKeyStoreUnauthenticatedAESCipherSpi$CBC$PKCS7Padding.finalize(AndroidKeyStoreUnauthenticatedAESCipherSpi.java)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:239)
	at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:226)
	at java.lang.Thread.run(Thread.java:761)
```
How to fix it?

**Comment by nic0lette** [comment]
The sample was ported to use BiometricPrompt and so I'm hopeful that this issue would be resolved. If it's still occurring, please open another issue.
