### ISSUE TITLE
Meizu crashed when using AndroidKeyStore

### ISSUE THREAD

**Issue by ramazan-olsoft** [android/security-samples#69]
There are crashes in some Meizu phones, such as M5 note, PRO 7 Plus and so on. The system version is Android 7.0. The log is:
`Fatal Exception: java.util.concurrent.TimeoutException: android.security.keystore.AndroidKeyStoreAuthenticatedAESCipherSpi$GCM$NoPadding.finalize() timed out after 20 seconds
       at android.os.BinderProxy.transactNative(Binder.java)
       at android.os.BinderProxy.transact(Binder.java:515)
       at android.security.IKeystoreService$Stub$Proxy.abort(IKeystoreService.java:1302)
       at android.security.KeyStore.abort(KeyStore.java:520)
       at android.security.keystore.AndroidKeyStoreCipherSpiBase.finalize(AndroidKeyStoreCipherSpiBase.java:680)
       at android.security.keystore.AndroidKeyStoreAuthenticatedAESCipherSpi$GCM$NoPadding.finalize(AndroidKeyStoreAuthenticatedAESCipherSpi.java:223)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:232)
       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:210)
       at java.lang.Thread.run(Thread.java:818)`
How to fix it?

**Comment by willmeet** [comment]
do you lost your keystore of your android app ? 

Then the simple solution >
http://www.technologymanias.com/2020/10/missing-or-lost-keystore-of-your.html

**Comment by willmeet** [comment]
do you lost your keystore of your android app ? 

Then the simple solution >
http://www.technologymanias.com/2020/10/missing-or-lost-keystore-of-your.html

**Comment by RamazanAriskaliev** [comment]
> do you lost your keystore of your android app ?
> 
> Then the simple solution >
> http://www.technologymanias.com/2020/10/missing-or-lost-keystore-of-your.html

No we didn't .

**Comment by ramazan-olsoft** [comment]
No we didn't.
