### ISSUE TITLE
Getting crash upon registering a new fingerprint on device

### ISSUE THREAD

**Issue by arpitasingh** [android/security-samples#76]
I registered on the sample app with my fingerprint and when I added a new fingerprint to the device, I could not login to app.

Error message:
 Caused by: android.security.keystore.KeyPermanentlyInvalidatedException: Key permanently invalidated.

Is this the expected behavior.
Posting the crash log hereby:

2021-03-23 12:23:14.961 7853-7853/com.example.biometricloginsample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.biometricloginsample, PID: 7853
    java.lang.RuntimeException: Unable to resume activity {com.example.biometricloginsample/com.example.biometricloginsample.LoginActivity}: android.security.keystore.KeyPermanentlyInvalidatedException: Key permanently invalidated
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3828)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3860)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: android.security.keystore.KeyPermanentlyInvalidatedException: Key permanently invalidated
        at android.security.KeyStore.getInvalidKeyException(KeyStore.java:907)
        at android.security.KeyStore.getInvalidKeyException(KeyStore.java:937)
        at android.security.keystore.KeyStoreCryptoOperationUtils.getInvalidKeyExceptionForInit(KeyStoreCryptoOperationUtils.java:54)
        at android.security.keystore.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:89)
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:268)
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:151)
        at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2980)
        at javax.crypto.Cipher.tryCombinations(Cipher.java:2891)
        at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2796)
        at javax.crypto.Cipher.chooseProvider(Cipher.java:773)
        at javax.crypto.Cipher.init(Cipher.java:1288)
        at javax.crypto.Cipher.init(Cipher.java:1223)
        at com.example.biometricloginsample.CryptographyManagerImpl.getInitializedCipherForDecryption(CryptographyManager.kt:93)
        at com.example.biometricloginsample.LoginActivity.showBiometricPromptForDecryption(LoginActivity.kt:96)
        at com.example.biometricloginsample.LoginActivity.onResume(LoginActivity.kt:82)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1413)
        at android.app.Activity.performResume(Activity.java:7400)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3820)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3860) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6810) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by arpitasingh** [comment]
I think, I need to handle the Invalid or KeyPermanentlyInvalidatedException.
